services:
  bohnanza-game:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0
      - LIBGL_ALWAYS_INDIRECT=true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    stdin_open: true
    tty: true
    command: [ "java", "-jar", "target/scala-3.3.3/Bohnanza.jar" ]
